### ISSUE TITLE
Client compile error on Ubuntu1204

### ISSUE THREAD

**Issue by xia0pin9** [iagox86/dnscat2#61]
I got the following error message when trying to compile the client:
```
drivers/driver_exec.c: In function ‘driver_exec_close’:
drivers/driver_exec.c:207:3: error: implicit declaration of function ‘kill’ [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make: *** [drivers/driver_exec.o] Error 1
```

**Comment by iagox86** [comment]
Hey, that should be easy to fix! I'm out of town with no laptop right now,
but I'll take of it early next week.

Thanks for the report!

**Comment by Retrospected** [comment]
i'm getting the same compile error, any news on this one ? :)

**Comment by iagox86** [comment]
Sorry, I just got back! :)

So, this is weird. It compiles on my Ubuntu machine, and I'm including the right headers. The only thing that might be causing it is a macro definition.. can you try this patch to see if it works?

    diff --git a/client/Makefile b/client/Makefile
    index 6a80616..9ba9d38 100644
    --- a/client/Makefile
    +++ b/client/Makefile
    @@ -9,7 +9,7 @@
     CC?=gcc
     DEBUG_CFLAGS?=-g -DTESTMEMORY -Werror -O0
     RELEASE_CFLAGS?=-Os
    -CFLAGS?=--std=c89 -I. -Wall -D_DEFAULT_SOURCE -fstack-protector-all -Wformat -Wformat-security
    +CFLAGS?=--std=c89 -I. -Wall -D_DEFAULT_SOURCE -fstack-protector-all -Wformat -Wformat-security -D_POSIX_SOURCE
     LIBS=-pie -Wl,-z,relro,-z,now
     
     # Can't use a '#' in the shell command

**Comment by alexwebr** [comment]
The above patch fixes the build on my 12.04 machine!

**Comment by iagox86** [comment]
Thanks Alex!

**Comment by iagox86** [comment]
Hmm, it turns out this breaks compilation on Cygwin (hooray for git bisect!) - stupid *nix. :)
